In [1]:
import os
import pandas as pd

# 構成銘柄一覧を正規化
nikkei_semiconductor_constituents = [
    {'Code': '4043', 'Name': 'トクヤマ', 'Sector': '化学'},
    {'Code': '4063', 'Name': '信越化学工業', 'Sector': '化学'},
    {'Code': '4186', 'Name': '東京応化工業', 'Sector': '化学'},
    {'Code': '4203', 'Name': '住友ベークライト', 'Sector': '化学'},
    {'Code': '4272', 'Name': '日本化薬', 'Sector': '化学'},
    {'Code': '4369', 'Name': 'トリケミカル研究所', 'Sector': '化学'},
    {'Code': '4401', 'Name': 'ＡＤＥＫＡ', 'Sector': '化学'},
    {'Code': '4626', 'Name': '太陽ホールディングス', 'Sector': '化学'},
    {'Code': '4980', 'Name': 'デクセリアルズ', 'Sector': '化学'},
    {'Code': '3436', 'Name': 'ＳＵＭＣＯ', 'Sector': '非鉄・金属'},
    {'Code': '6315', 'Name': 'ＴＯＷＡ', 'Sector': '機械'},
    {'Code': '6323', 'Name': 'ローツェ', 'Sector': '機械'},
    {'Code': '6526', 'Name': 'ソシオネクスト', 'Sector': '電気機器'}, 
    {'Code': '6707', 'Name': 'サンケン電気', 'Sector': '電気機器'},
    {'Code': '6723', 'Name': 'ルネサスエレクトロニクス', 'Sector': '電気機器'},
    {'Code': '6728', 'Name': 'アルバック', 'Sector': '電気機器'},
    {'Code': '6758', 'Name': 'ソニーグループ', 'Sector': '電気機器'},
    {'Code': '6857', 'Name': 'アドバンテスト', 'Sector': '電気機器'},
    {'Code': '6890', 'Name': 'フェローテックホールディングス', 'Sector': '電気機器'},
    {'Code': '6920', 'Name': 'レーザーテック', 'Sector': '電気機器'},
    {'Code': '6963', 'Name': 'ローム', 'Sector': '電気機器'},
    {'Code': '7735', 'Name': 'ＳＣＲＥＥＮホールディングス', 'Sector': '電気機器'},
    {'Code': '8035', 'Name': '東京エレクトロン', 'Sector': '電気機器'},
    {'Code': '6146', 'Name': 'ディスコ', 'Sector': '精密機器'},
    {'Code': '7729', 'Name': '東京精密', 'Sector': '精密機器'},
    {'Code': '7741', 'Name': 'ＨＯＹＡ', 'Sector': '精密機器'},
    {'Code': '2760', 'Name': '東京エレクトロン　デバイス', 'Sector': '商社'},
    {'Code': '3132', 'Name': 'マクニカホールディングス', 'Sector': '商社'},
    {'Code': '8154', 'Name': '加賀電子', 'Sector': '商社'}
]

df_constituents = pd.DataFrame(nikkei_semiconductor_constituents)

# 構成銘柄一覧を保存
STORAGE_DIR_PATH = fr"C:\Users\100ca\Documents\PyCode\jquants-api-client-python\code\data"

constituents_file = f"{STORAGE_DIR_PATH}/nikkei_semiconductor_constituents.csv"
df_constituents.to_csv(constituents_file, index=False)

In [2]:
refresh_token = "eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.N8MYP3Ckh3ajJhVrdxthB5EhawxMdq_0xsuK88oWEWMWSI1Bqqd0Lnw059CUAa9cpiz4dnBe8u9xaRH45s2MAkEGYlJKFSPI_g6xBI3uvFwq1UjliwVDPYk4S00eGy4PNcuoJU-XPl_YPZjkoVZMNyKBxJVQanKsUZOuLsm4RitdPc9FPDN6YbWJM4-3aQ3XsuWcpk7dtBtK2y4emKQ5eHXZ2WDqkn4TzAroeAwFXNUS3Sbj7JLT_eV8mvCF4pFgMNjR3YAMmEZOZiXXs7HPS9QIEviarKJ-qa7V_fyW5ns3Lhsbaj_2oG-yNwGGo7qb7YbENQDqIan7avmXqV8T_A.xncrf9wyZKL3Zpec.xCr-HTBZ0jBYtGkihfP5LdrvICHIXhDeTMT6SG-IU-k8pJOGkQvdvrJlicvcShPsXYVdKom6gtSJgsIxe75J66R--hPn3V5Z9Mf1XxeTBg5gEkShbxqMGGJfHCVt7xOnEuR5mTwvJaZzplNg43F31icVUCWrtpQueQ0pbhBqeIYBYFmA4BFHWvblNU-KzF7Ue5MxGv1_f38stAOeU9_ELVt0hinVnSoNu-Lq0HtGUEtLsh12zgGx_lK9_Ars1pCoTwGtKeALxxNeLCX5fPvOPNsdiddq_3JGDTK2dQXle31ylpRCMhJcAVrL3BJumPU4vdEjq5fARY6VtC3grGuAZZGLtaYxRYPfEZh-ifheWF1MgEdtA85d0UWwZOiKqIQhDBaLS2rq_1l0glgnf47dQJkzrdZldb7vEWhQZ8J-FETXrW1KkYb2DV-hu2-_9jtYfjd4ixAFCJuQ1OC5we0XUVXtPhxfPp0k15jlarXpPhe9thSsNPNDEafMm5hFNCXrXDnz5vy5hFEvwlofB3iXPfF8GoWTmkut5Biqd5ZT0wBhdKiKywCd358Nq0VbZLzBet0dxEtPQGQB-zUSSIQG08ChcCV_GzdQXoVO3qJQjb7X2cUpby-L6OZgPMGNEEzH-7xHNf3BY9B_YQPtvQWrUG4UIYpQ_4yFoKi0Zd2a39swsAPt_zv_j0fHD5ocefz2xmyFVIm53Sah4wuSQJqEwNVMAMyEZWem4wEqtuaVLmxtUj6ilDyyPeRwu_w-nagsUkIEmg1UH8JxoloKJQvSA3any0BVh9s9IB7LleBur62pCvJQreBfczVJ8PrD1YOPVNFAJF3RKL-UswAb2egUytB8GwZQK9EnmvYxGfRRYlWYC1g8s22bBnETMYbA2qXGRYZzweZt4zngAO4EuUpUIDDrs9f-8d__8F3O6ls0rQUZ6WBOSpHSkSNqKC7I9BswRoD-TbVrbdZGyYNf25mojKZfyq9BJiXADSZU2UyShAUKG80oPmePBUgWvi6erTIHkE18YKxe_xuazaijHlYBHSyJ-4US9kR4PNOxA0vIyfWl7jKsgUv1ofSQSeMJ9PxigF0DvIG9089HzGxBdzZlVJPXtQb9I3MhVK0UHJwZ7BmX4DlcoMrWaCtGo9zd4L33PQ_iB0GsmnngFlIaaRzOZo3oLZrFAhJ6uYfN9UqsOlic_sL75IsJF4IE6klZafakLBGef0EHJKdzf9_QiZx5TPigGV0wr63BHTlDRqcOtyB4XOBp9CqngRvxSc-9_-Qc3k1a05u2ODrgaSl70iuAUjDOQxuDdhPr5kIscv6xyQwtqsHJb_gL_GMRLZAUnULoq7WMZnfUipWFEQ.PJ1iLNhPGLuzCmg1HrueDA"#@param {type: "string"}

In [3]:
import os
import pandas as pd
import jquantsapi

# JQuants APIクライアントの初期化 (ご自身の認証情報を使用してください)
jqapi = jquantsapi.Client(refresh_token=refresh_token)

# 保存した構成銘柄一覧を読み込み
constituents_file = f"{STORAGE_DIR_PATH}/nikkei_semiconductor_constituents.csv"
if os.path.exists(constituents_file):
    df_constituents = pd.read_csv(constituents_file)
    nikkei_semiconductor_codes = df_constituents['Code'].tolist()
else:
    raise FileNotFoundError(f"構成銘柄一覧ファイルが見つかりません: {constituents_file}")

# 財務データ取得の開始日と終了日を設定
now = pd.Timestamp.now(tz="Asia/Tokyo")
start_dt = now - pd.Timedelta(700, unit="D") 
end_dt = now - pd.Timedelta(85, unit="D")
if end_dt.hour < 1:
    end_dt -= pd.Timedelta(1, unit="D")

# 日経半導体株指数構成銘柄の財務データを取得
df_nikkei_semiconductor_fin = pd.DataFrame()
for code in nikkei_semiconductor_codes:
    df_fin = jqapi.get_fins_statements(code=code)
    
    # タイムゾーン情報を設定
    df_fin['DisclosedDate'] = pd.to_datetime(df_fin['DisclosedDate']).dt.tz_localize('Asia/Tokyo')
    df_fin['CurrentPeriodEndDate'] = pd.to_datetime(df_fin['CurrentPeriodEndDate']).dt.tz_localize('Asia/Tokyo')
    df_fin['CurrentFiscalYearStartDate'] = pd.to_datetime(df_fin['CurrentFiscalYearStartDate']).dt.tz_localize('Asia/Tokyo')
    df_fin['CurrentFiscalYearEndDate'] = pd.to_datetime(df_fin['CurrentFiscalYearEndDate']).dt.tz_localize('Asia/Tokyo')
    
    df_fin = df_fin[(df_fin['DisclosedDate'] >= start_dt) & (df_fin['DisclosedDate'] <= end_dt)]
    
    # 'Code' 列を追加
    df_fin['Code'] = code
    
    df_nikkei_semiconductor_fin = pd.concat([df_nikkei_semiconductor_fin, df_fin])

# 日付でソート  
df_nikkei_semiconductor_fin.sort_values(["DisclosedDate", "DisclosedTime"], inplace=True)

# 結果を保存
statements_file = f"{STORAGE_DIR_PATH}/nikkei_semiconductor_statements_{start_dt.strftime('%Y%m%d')}_{end_dt.strftime('%Y%m%d')}.csv" 
df_nikkei_semiconductor_fin.to_csv(statements_file, index=False)

# 保存したファイルを読み込み、欠損値処理と銘柄名の追加
df_nikkei_semiconductor_fin = pd.read_csv(statements_file)
df_nikkei_semiconductor_fin.dropna(how='all', axis=0, inplace=True)  # 行方向の欠損値処理
df_nikkei_semiconductor_fin.dropna(how='all', axis=1, inplace=True)  # 列方向の欠損値処理
df_nikkei_semiconductor_fin = pd.merge(df_nikkei_semiconductor_fin, df_constituents, on='Code', how='left')  # 銘柄名の追加

# 最終結果を保存
final_statements_file = f"{STORAGE_DIR_PATH}/nikkei_semiconductor_statements_final_{start_dt.strftime('%Y%m%d')}_{end_dt.strftime('%Y%m%d')}.csv"
df_nikkei_semiconductor_fin.to_csv(final_statements_file, index=False)

# データの読み込み
df = pd.read_csv(final_statements_file)

# 日時データをdatetime形式に変換
date_cols = ['DisclosedDate', 'CurrentPeriodEndDate', 'CurrentFiscalYearStartDate', 'CurrentFiscalYearEndDate', 'NextFiscalYearStartDate', 'NextFiscalYearEndDate']
for col in date_cols:
    df[col] = pd.to_datetime(df[col])

# 時刻データをdatetime形式に変換
df['DisclosedTime'] = pd.to_datetime(df['DisclosedTime']).dt.time

# 'DisclosedDate' と 'DisclosedTime' を結合して新しいカラムを作成
df['DisclosedDateTime'] = pd.to_datetime(df['DisclosedDate'].astype(str) + ' ' + df['DisclosedTime'].astype(str))

# 'DisclosedDateTime' をインデックスに設定
df.set_index('DisclosedDateTime', inplace=True)

# 必要なカラムだけ抽出
df_sorted = df[['Name', 'NetSales', 'OperatingProfit', 'OrdinaryProfit', 'Profit']].sort_index().sort_values(by=["Name"]).dropna(axis=0,subset="NetSales")

# 結果の表示
print(df_sorted)

# 結果の保存
df_sorted.to_csv(fr"{STORAGE_DIR_PATH}/nikkei_semiconductor_sorted.csv", index=True)

                              Name      NetSales  OperatingProfit  \
DisclosedDateTime
2023-07-26 15:00:00+09:00  アドバンテスト  1.012510e+11     1.426900e+10
2023-10-31 15:00:00+09:00  アドバンテスト  2.175110e+11     3.526900e+10
2023-01-31 15:00:00+09:00  アドバンテスト  4.127990e+11     1.291400e+11
2022-10-27 15:00:00+09:00  アドバンテスト  2.748060e+11     8.791600e+10
2024-01-31 15:00:00+09:00  アドバンテスト  3.507440e+11     6.209900e+10
...                            ...           ...              ...
2023-05-11 15:30:00+09:00     ＴＯＷＡ  5.382200e+10     1.003700e+10
2024-02-07 15:30:00+09:00     ＴＯＷＡ  3.203200e+10     4.075000e+09
2023-11-08 15:30:00+09:00     ＴＯＷＡ  2.126500e+10     2.388000e+09
2023-02-07 15:30:00+09:00     ＴＯＷＡ  4.017100e+10     7.513000e+09
2022-08-08 15:30:00+09:00     ＴＯＷＡ  1.459200e+10     2.859000e+09

                           OrdinaryProfit        Profit
DisclosedDateTime
2023-07-26 15:00:00+09:00             NaN  9.202000e+09
2023-10-31 15:00:00+09:00             NaN  2.593800e+10
2023-01-31 15:00:00+09:00             NaN  9.980600e+10
2022-10-27 15:00:00+09:00             NaN  7.116100e+10
2024-01-31 15:00:00+09:00             NaN  4.714300e+10
...                                   ...           ...
2023-05-11 15:30:00+09:00    1.020600e+10  7.346000e+09
2024-02-07 15:30:00+09:00    4.318000e+09  3.112000e+09
2023-11-08 15:30:00+09:00    2.763000e+09  1.958000e+09
2023-02-07 15:30:00+09:00    7.662000e+09  5.631000e+09
2022-08-08 15:30:00+09:00    3.223000e+09  2.357000e+09

[202 rows x 5 columns]

In [4]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib as mpl

# データの読み込み
df_sorted = pd.read_csv(fr"{STORAGE_DIR_PATH}/nikkei_semiconductor_sorted.csv", parse_dates=['DisclosedDateTime'])

# 'DisclosedDateTime' をインデックスに設定してソート
df_sorted.set_index('DisclosedDateTime', inplace=True)
df_sorted = df_sorted.sort_index().dropna(axis=0,subset="NetSales")

# 'Name'ごとにグループ化
grouped = df_sorted.groupby('Name')

# 画像の保存先ディレクトリを設定
output_dir = os.path.join(STORAGE_DIR_PATH, 'graphs')
os.makedirs(output_dir, exist_ok=True)

# 日本語フォントの設定
mpl.rcParams['font.family'] = 'Yu Gothic'

# 'Name'ごとにプロット
for name, group in grouped:
    plt.figure(figsize=(14, 8))
    
    # 各数値を折れ線グラフでプロット
    plt.plot(group.index, group['NetSales'], marker='o', label='売上高')
    plt.plot(group.index, group['OperatingProfit'], marker='o', label='営業利益')
    plt.plot(group.index, group['OrdinaryProfit'], marker='o', label='経常利益')
    plt.plot(group.index, group['Profit'], marker='o', label='純利益')
    
    plt.xlabel('日付', fontsize=12)
    plt.ylabel('金額 (円)', fontsize=12)
    plt.title(f'{name}の財務データ', fontsize=14)
    plt.legend()
    plt.xticks(rotation=45)
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.grid(True)
    
    # グラフを保存
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, f'{name}.png'), dpi=300)
    plt.close()

print("グラフが正常に保存されました。")

グラフが正常に保存されました。

In [18]:
df_sorted[df_sorted["Name"]=="アドバンテスト"]

,Name,NetSales,OperatingProfit,OrdinaryProfit,Profit
DisclosedDateTime,,,,,
2022-07-28 15:00:00+09:00,アドバンテスト,1.359430e+11,4.478300e+10,NaN,3.649600e+10
2022-10-27 15:00:00+09:00,アドバンテスト,2.748060e+11,8.791600e+10,NaN,7.116100e+10
2023-01-31 15:00:00+09:00,アドバンテスト,4.127990e+11,1.291400e+11,NaN,9.980600e+10
2023-04-26 15:00:00+09:00,アドバンテスト,5.601910e+11,1.676870e+11,NaN,1.304000e+11
2023-07-26 15:00:00+09:00,アドバンテスト,1.012510e+11,1.426900e+10,NaN,9.202000e+09
2023-10-31 15:00:00+09:00,アドバンテスト,2.175110e+11,3.526900e+10,NaN,2.593800e+10
2024-01-31 15:00:00+09:00,アドバンテスト,3.507440e+11,6.209900e+10,NaN,4.714300e+10

In [19]:
df_nikkei_semiconductor_fin[df_nikkei_semiconductor_fin["Name"]=="アドバンテスト"][['DisclosedDate','Name',	'NetSales',	'OperatingProfit',	'OrdinaryProfit',	'Profit']]

,DisclosedDate,Name,NetSales,OperatingProfit,OrdinaryProfit,Profit
7,2022-07-28 00:00:00+09:00,アドバンテスト,1.359430e+11,4.478300e+10,NaN,3.649600e+10
36,2022-10-27 00:00:00+09:00,アドバンテスト,2.748060e+11,8.791600e+10,NaN,7.116100e+10
70,2023-01-31 00:00:00+09:00,アドバンテスト,4.127990e+11,1.291400e+11,NaN,9.980600e+10
100,2023-04-26 00:00:00+09:00,アドバンテスト,5.601910e+11,1.676870e+11,NaN,1.304000e+11
134,2023-07-26 00:00:00+09:00,アドバンテスト,1.012510e+11,1.426900e+10,NaN,9.202000e+09
173,2023-10-31 00:00:00+09:00,アドバンテスト,2.175110e+11,3.526900e+10,NaN,2.593800e+10
202,2024-01-31 00:00:00+09:00,アドバンテスト,3.507440e+11,6.209900e+10,NaN,4.714300e+10

In [23]:
jqapi.get_fins_statements(code="6857")[['DisclosedDate',	'NetSales',	'OperatingProfit',	'OrdinaryProfit',	'Profit']]

  DisclosedDate      NetSales OperatingProfit OrdinaryProfit        Profit
0    2022-04-27  416901000000    114734000000                  87301000000
1    2022-07-28  135943000000     44783000000                  36496000000
2    2022-10-27  274806000000     87916000000                  71161000000
3    2023-01-31  412799000000    129140000000                  99806000000
4    2023-04-26  560191000000    167687000000                 130400000000
5    2023-07-26  101251000000     14269000000                   9202000000
6    2023-10-31  217511000000     35269000000                  25938000000
7    2024-01-31  350744000000     62099000000                  47143000000

# https://kabutan.jp/stock/finance?code=6857

3ヵ月決算【実績】

決算期	売上高	営業益	経常益	最終益	修正1株益	売上営業
損益率	発表日
I  　 22.04-06  	135,943	44,783	48,416	36,496	48.0	32.9	22/07/28
I  　 22.07-09  	138,863	43,133	46,831	34,665	45.7	31.1	22/10/27
I  　 22.10-12  	137,993	41,224	37,611	28,645	38.1	29.9	23/01/31
I  　 23.01-03  	147,392	38,547	38,412	30,594	40.9	26.2	23/04/26
I  　 23.04-06  	101,251	14,269	12,961	9,202	12.5	14.1	23/07/26
I  　 23.07-09  	116,260	21,000	20,356	16,736	22.7	18.1	23/10/31
I  　 23.10-12  	133,233	26,830	26,250	21,205	28.8	20.1	24/01/31
I  　 24.01-03  	135,763	19,529	18,603	15,147	20.5	14.4	24/04/26